"""Add fields to image model

Revision ID: 097d21b5926d
Revises: 88e0777faa4e
Create Date: 2021-11-04 20:38:46.830629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097d21b5926d'
down_revision = '88e0777faa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('ratio', sa.Float(), nullable=True))
    op.add_column('image', sa.Column('hash', sa.VARBINARY(length=27), nullable=True))
    op.create_index(op.f('ix_image_ratio'), 'image', ['ratio'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_ratio'), table_name='image')
    op.drop_column('image', 'hash')
    op.drop_column('image', 'ratio')
    op.drop_column('image', 'width')
    op.drop_column('image', 'height')
    # ### end Alembic commands ###
