"""Add index to hash in image model

Revision ID: bba61ce5ff73
Revises: 097d21b5926d
Create Date: 2021-11-04 20:44:40.716672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba61ce5ff73'
down_revision = '097d21b5926d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_image_hash'), 'image', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_hash'), table_name='image')
    # ### end Alembic commands ###
